// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: controller.proto
#ifndef GRPC_controller_2eproto__INCLUDED
#define GRPC_controller_2eproto__INCLUDED

#include "controller.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace Controller {

class ControllerService final {
 public:
  static constexpr char const* service_full_name() {
    return "Controller.ControllerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::Controller::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>> AsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>>(AsyncRouteRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>> PrepareAsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>>(PrepareAsyncRouteRegisterFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::Controller::IdentifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>> AsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>>(AsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>> PrepareAsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>>(PrepareAsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::Controller::VerifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>> AsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>>(AsyncRouteVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>> PrepareAsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>>(PrepareAsyncRouteVerifyFaceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>* AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::RegisterReply>* PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>* AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::IdentifyReply>* PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>* AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Controller::VerifyReply>* PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::Controller::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>> AsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>>(AsyncRouteRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>> PrepareAsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>>(PrepareAsyncRouteRegisterFaceRaw(context, request, cq));
    }
    ::grpc::Status RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::Controller::IdentifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>> AsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>>(AsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>> PrepareAsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>>(PrepareAsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    ::grpc::Status RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::Controller::VerifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>> AsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>>(AsyncRouteVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>> PrepareAsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>>(PrepareAsyncRouteVerifyFaceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, std::function<void(::grpc::Status)>) override;
      void RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, std::function<void(::grpc::Status)>) override;
      void RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, std::function<void(::grpc::Status)>) override;
      void RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>* AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>* PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>* AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>* PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>* AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>* PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RouteRegisterFace_;
    const ::grpc::internal::RpcMethod rpcmethod_RouteIdentifyFace_;
    const ::grpc::internal::RpcMethod rpcmethod_RouteVerifyFace_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RouteRegisterFace(::grpc::ServerContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response);
    virtual ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response);
    virtual ::grpc::Status RouteVerifyFace(::grpc::ServerContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteRegisterFace(::grpc::ServerContext* context, ::Controller::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::Controller::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteIdentifyFace(::grpc::ServerContext* context, ::Controller::IdentifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::Controller::IdentifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteVerifyFace(::grpc::ServerContext* context, ::Controller::VerifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::Controller::VerifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RouteRegisterFace<WithAsyncMethod_RouteIdentifyFace<WithAsyncMethod_RouteVerifyFace<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Controller::RegisterRequest, ::Controller::RegisterReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response) { return this->RouteRegisterFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteRegisterFace(
        ::grpc::MessageAllocator< ::Controller::RegisterRequest, ::Controller::RegisterReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Controller::RegisterRequest, ::Controller::RegisterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteRegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Controller::IdentifyRequest, ::Controller::IdentifyReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response) { return this->RouteIdentifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteIdentifyFace(
        ::grpc::MessageAllocator< ::Controller::IdentifyRequest, ::Controller::IdentifyReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Controller::IdentifyRequest, ::Controller::IdentifyReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteIdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::Controller::VerifyRequest, ::Controller::VerifyReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response) { return this->RouteVerifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteVerifyFace(
        ::grpc::MessageAllocator< ::Controller::VerifyRequest, ::Controller::VerifyReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Controller::VerifyRequest, ::Controller::VerifyReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteVerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RouteRegisterFace<WithCallbackMethod_RouteIdentifyFace<WithCallbackMethod_RouteVerifyFace<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteRegisterFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteIdentifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteVerifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteRegisterFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteRegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteIdentifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteIdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteVerifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteVerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Controller::RegisterRequest, ::Controller::RegisterReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Controller::RegisterRequest, ::Controller::RegisterReply>* streamer) {
                       return this->StreamedRouteRegisterFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Controller::RegisterRequest* /*request*/, ::Controller::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteRegisterFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Controller::RegisterRequest,::Controller::RegisterReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Controller::IdentifyRequest, ::Controller::IdentifyReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Controller::IdentifyRequest, ::Controller::IdentifyReply>* streamer) {
                       return this->StreamedRouteIdentifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Controller::IdentifyRequest* /*request*/, ::Controller::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteIdentifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Controller::IdentifyRequest,::Controller::IdentifyReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Controller::VerifyRequest, ::Controller::VerifyReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Controller::VerifyRequest, ::Controller::VerifyReply>* streamer) {
                       return this->StreamedRouteVerifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Controller::VerifyRequest* /*request*/, ::Controller::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteVerifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Controller::VerifyRequest,::Controller::VerifyReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RouteRegisterFace<WithStreamedUnaryMethod_RouteIdentifyFace<WithStreamedUnaryMethod_RouteVerifyFace<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RouteRegisterFace<WithStreamedUnaryMethod_RouteIdentifyFace<WithStreamedUnaryMethod_RouteVerifyFace<Service > > > StreamedService;
};

}  // namespace Controller


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_controller_2eproto__INCLUDED
