// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: controller.proto

#include "controller.pb.h"
#include "controller.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace Controller {

static const char* ControllerService_method_names[] = {
  "/Controller.ControllerService/RouteRegisterFace",
  "/Controller.ControllerService/RouteIdentifyFace",
  "/Controller.ControllerService/RouteVerifyFace",
};

std::unique_ptr< ControllerService::Stub> ControllerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControllerService::Stub> stub(new ControllerService::Stub(channel, options));
  return stub;
}

ControllerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RouteRegisterFace_(ControllerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RouteIdentifyFace_(ControllerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RouteVerifyFace_(ControllerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ControllerService::Stub::RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::Controller::RegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Controller::RegisterRequest, ::Controller::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteRegisterFace_, context, request, response);
}

void ControllerService::Stub::async::RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Controller::RegisterRequest, ::Controller::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteRegisterFace_, context, request, response, std::move(f));
}

void ControllerService::Stub::async::RouteRegisterFace(::grpc::ClientContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteRegisterFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>* ControllerService::Stub::PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Controller::RegisterReply, ::Controller::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteRegisterFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Controller::RegisterReply>* ControllerService::Stub::AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Controller::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteRegisterFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControllerService::Stub::RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::Controller::IdentifyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Controller::IdentifyRequest, ::Controller::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteIdentifyFace_, context, request, response);
}

void ControllerService::Stub::async::RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Controller::IdentifyRequest, ::Controller::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteIdentifyFace_, context, request, response, std::move(f));
}

void ControllerService::Stub::async::RouteIdentifyFace(::grpc::ClientContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteIdentifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>* ControllerService::Stub::PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Controller::IdentifyReply, ::Controller::IdentifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteIdentifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Controller::IdentifyReply>* ControllerService::Stub::AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Controller::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteIdentifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControllerService::Stub::RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::Controller::VerifyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Controller::VerifyRequest, ::Controller::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteVerifyFace_, context, request, response);
}

void ControllerService::Stub::async::RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Controller::VerifyRequest, ::Controller::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteVerifyFace_, context, request, response, std::move(f));
}

void ControllerService::Stub::async::RouteVerifyFace(::grpc::ClientContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteVerifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>* ControllerService::Stub::PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Controller::VerifyReply, ::Controller::VerifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteVerifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Controller::VerifyReply>* ControllerService::Stub::AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Controller::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteVerifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

ControllerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControllerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControllerService::Service, ::Controller::RegisterRequest, ::Controller::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControllerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Controller::RegisterRequest* req,
             ::Controller::RegisterReply* resp) {
               return service->RouteRegisterFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControllerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControllerService::Service, ::Controller::IdentifyRequest, ::Controller::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControllerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Controller::IdentifyRequest* req,
             ::Controller::IdentifyReply* resp) {
               return service->RouteIdentifyFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControllerService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControllerService::Service, ::Controller::VerifyRequest, ::Controller::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControllerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Controller::VerifyRequest* req,
             ::Controller::VerifyReply* resp) {
               return service->RouteVerifyFace(ctx, req, resp);
             }, this)));
}

ControllerService::Service::~Service() {
}

::grpc::Status ControllerService::Service::RouteRegisterFace(::grpc::ServerContext* context, const ::Controller::RegisterRequest* request, ::Controller::RegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControllerService::Service::RouteIdentifyFace(::grpc::ServerContext* context, const ::Controller::IdentifyRequest* request, ::Controller::IdentifyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControllerService::Service::RouteVerifyFace(::grpc::ServerContext* context, const ::Controller::VerifyRequest* request, ::Controller::VerifyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Controller
#include <grpcpp/ports_undef.inc>

