# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import controller_pb2 as controller__pb2


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/controller.ControllerService/Identify',
                request_serializer=controller__pb2.IdentifyRequest.SerializeToString,
                response_deserializer=controller__pb2.IdentifyResponse.FromString,
                )
        self.VerifyFaces = channel.unary_unary(
                '/controller.ControllerService/VerifyFaces',
                request_serializer=controller__pb2.VerifyRequest.SerializeToString,
                response_deserializer=controller__pb2.VerifyResponse.FromString,
                )
        self.RegisterFace = channel.unary_unary(
                '/controller.ControllerService/RegisterFace',
                request_serializer=controller__pb2.RegisterRequest.SerializeToString,
                response_deserializer=controller__pb2.RegisterResponse.FromString,
                )


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Identify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=controller__pb2.IdentifyRequest.FromString,
                    response_serializer=controller__pb2.IdentifyResponse.SerializeToString,
            ),
            'VerifyFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyFaces,
                    request_deserializer=controller__pb2.VerifyRequest.FromString,
                    response_serializer=controller__pb2.VerifyResponse.SerializeToString,
            ),
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=controller__pb2.RegisterRequest.FromString,
                    response_serializer=controller__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ControllerService/Identify',
            controller__pb2.IdentifyRequest.SerializeToString,
            controller__pb2.IdentifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ControllerService/VerifyFaces',
            controller__pb2.VerifyRequest.SerializeToString,
            controller__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.ControllerService/RegisterFace',
            controller__pb2.RegisterRequest.SerializeToString,
            controller__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
