// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: driver.proto

#include "driver.pb.h"
#include "driver.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace Driver {

static const char* DriverService_method_names[] = {
  "/Driver.DriverService/RouteIdentifyFace",
  "/Driver.DriverService/RouteVerifyFace",
  "/Driver.DriverService/RouteRegisterFace",
};

std::unique_ptr< DriverService::Stub> DriverService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DriverService::Stub> stub(new DriverService::Stub(channel, options));
  return stub;
}

DriverService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RouteIdentifyFace_(DriverService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RouteVerifyFace_(DriverService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RouteRegisterFace_(DriverService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DriverService::Stub::RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::Driver::IdentifyResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Driver::ImageQuery, ::Driver::IdentifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteIdentifyFace_, context, request, response);
}

void DriverService::Stub::async::RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Driver::ImageQuery, ::Driver::IdentifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteIdentifyFace_, context, request, response, std::move(f));
}

void DriverService::Stub::async::RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteIdentifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>* DriverService::Stub::PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Driver::IdentifyResult, ::Driver::ImageQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteIdentifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>* DriverService::Stub::AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteIdentifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DriverService::Stub::RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::Driver::VerifyResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Driver::VerifyImagePair, ::Driver::VerifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteVerifyFace_, context, request, response);
}

void DriverService::Stub::async::RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Driver::VerifyImagePair, ::Driver::VerifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteVerifyFace_, context, request, response, std::move(f));
}

void DriverService::Stub::async::RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteVerifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>* DriverService::Stub::PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Driver::VerifyResult, ::Driver::VerifyImagePair, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteVerifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>* DriverService::Stub::AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteVerifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DriverService::Stub::RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::Driver::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Driver::RegisterRequest, ::Driver::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RouteRegisterFace_, context, request, response);
}

void DriverService::Stub::async::RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Driver::RegisterRequest, ::Driver::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteRegisterFace_, context, request, response, std::move(f));
}

void DriverService::Stub::async::RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RouteRegisterFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>* DriverService::Stub::PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Driver::RegisterResponse, ::Driver::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RouteRegisterFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>* DriverService::Stub::AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRouteRegisterFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

DriverService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DriverService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DriverService::Service, ::Driver::ImageQuery, ::Driver::IdentifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DriverService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Driver::ImageQuery* req,
             ::Driver::IdentifyResult* resp) {
               return service->RouteIdentifyFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DriverService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DriverService::Service, ::Driver::VerifyImagePair, ::Driver::VerifyResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DriverService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Driver::VerifyImagePair* req,
             ::Driver::VerifyResult* resp) {
               return service->RouteVerifyFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DriverService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DriverService::Service, ::Driver::RegisterRequest, ::Driver::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DriverService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Driver::RegisterRequest* req,
             ::Driver::RegisterResponse* resp) {
               return service->RouteRegisterFace(ctx, req, resp);
             }, this)));
}

DriverService::Service::~Service() {
}

::grpc::Status DriverService::Service::RouteIdentifyFace(::grpc::ServerContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DriverService::Service::RouteVerifyFace(::grpc::ServerContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DriverService::Service::RouteRegisterFace(::grpc::ServerContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Driver
#include <grpcpp/ports_undef.inc>

