# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import driver_pb2 as driver__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteIdentify = channel.unary_unary(
                '/driver.DriverService/RouteIdentify',
                request_serializer=driver__pb2.ImageQuery.SerializeToString,
                response_deserializer=driver__pb2.IdentifyResult.FromString,
                _registered_method=True)
        self.RouteVerify = channel.unary_unary(
                '/driver.DriverService/RouteVerify',
                request_serializer=driver__pb2.VerifyImagePair.SerializeToString,
                response_deserializer=driver__pb2.VerifyResult.FromString,
                _registered_method=True)
        self.RegisterFace = channel.unary_unary(
                '/driver.DriverService/RegisterFace',
                request_serializer=driver__pb2.RegisterRequest.SerializeToString,
                response_deserializer=driver__pb2.RegisterResponse.FromString,
                _registered_method=True)


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteIdentify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteIdentify': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteIdentify,
                    request_deserializer=driver__pb2.ImageQuery.FromString,
                    response_serializer=driver__pb2.IdentifyResult.SerializeToString,
            ),
            'RouteVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteVerify,
                    request_deserializer=driver__pb2.VerifyImagePair.FromString,
                    response_serializer=driver__pb2.VerifyResult.SerializeToString,
            ),
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=driver__pb2.RegisterRequest.FromString,
                    response_serializer=driver__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'driver.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('driver.DriverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteIdentify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/RouteIdentify',
            driver__pb2.ImageQuery.SerializeToString,
            driver__pb2.IdentifyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/RouteVerify',
            driver__pb2.VerifyImagePair.SerializeToString,
            driver__pb2.VerifyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/RegisterFace',
            driver__pb2.RegisterRequest.SerializeToString,
            driver__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
