# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import driver_pb2 as driver__pb2


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteIdentify = channel.unary_unary(
                '/driver.DriverService/RouteIdentify',
                request_serializer=driver__pb2.ImageQuery.SerializeToString,
                response_deserializer=driver__pb2.IdentifyResult.FromString,
                )
        self.RouteVerify = channel.unary_unary(
                '/driver.DriverService/RouteVerify',
                request_serializer=driver__pb2.VerifyImagePair.SerializeToString,
                response_deserializer=driver__pb2.VerifyResult.FromString,
                )
        self.RegisterFace = channel.unary_unary(
                '/driver.DriverService/RegisterFace',
                request_serializer=driver__pb2.RegisterRequest.SerializeToString,
                response_deserializer=driver__pb2.RegisterResponse.FromString,
                )


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteIdentify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteIdentify': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteIdentify,
                    request_deserializer=driver__pb2.ImageQuery.FromString,
                    response_serializer=driver__pb2.IdentifyResult.SerializeToString,
            ),
            'RouteVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteVerify,
                    request_deserializer=driver__pb2.VerifyImagePair.FromString,
                    response_serializer=driver__pb2.VerifyResult.SerializeToString,
            ),
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=driver__pb2.RegisterRequest.FromString,
                    response_serializer=driver__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'driver.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteIdentify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/driver.DriverService/RouteIdentify',
            driver__pb2.ImageQuery.SerializeToString,
            driver__pb2.IdentifyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RouteVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/driver.DriverService/RouteVerify',
            driver__pb2.VerifyImagePair.SerializeToString,
            driver__pb2.VerifyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/driver.DriverService/RegisterFace',
            driver__pb2.RegisterRequest.SerializeToString,
            driver__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
