# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2
from proto import executor_pb2 as executor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x06\x64river\x1a\x0c\x63ommon.proto\x1a\x0e\x65xecutor.proto\" \n\nImageQuery\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"p\n\x0eIdentifyResult\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t\x12(\n\x0btop_matches\x18\x04 \x03(\x0b\x32\x13.executor.FaceMatch\"1\n\x0fVerifyImagePair\x12\x0e\n\x06image1\x18\x01 \x01(\x0c\x12\x0e\n\x06image2\x18\x02 \x01(\x0c\"2\n\x0cVerifyResult\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x12\x0e\n\x06result\x18\x02 \x01(\t\"6\n\x0fRegisterRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcd\x01\n\rDriverService\x12;\n\rRouteIdentify\x12\x12.driver.ImageQuery\x1a\x16.driver.IdentifyResult\x12<\n\x0bRouteVerify\x12\x17.driver.VerifyImagePair\x1a\x14.driver.VerifyResult\x12\x41\n\x0cRegisterFace\x12\x17.driver.RegisterRequest\x1a\x18.driver.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEQUERY']._serialized_start=54
  _globals['_IMAGEQUERY']._serialized_end=86
  _globals['_IDENTIFYRESULT']._serialized_start=88
  _globals['_IDENTIFYRESULT']._serialized_end=200
  _globals['_VERIFYIMAGEPAIR']._serialized_start=202
  _globals['_VERIFYIMAGEPAIR']._serialized_end=251
  _globals['_VERIFYRESULT']._serialized_start=253
  _globals['_VERIFYRESULT']._serialized_end=303
  _globals['_REGISTERREQUEST']._serialized_start=305
  _globals['_REGISTERREQUEST']._serialized_end=359
  _globals['_REGISTERRESPONSE']._serialized_start=361
  _globals['_REGISTERRESPONSE']._serialized_end=413
  _globals['_DRIVERSERVICE']._serialized_start=416
  _globals['_DRIVERSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
