// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: driver.proto
#ifndef GRPC_driver_2eproto__INCLUDED
#define GRPC_driver_2eproto__INCLUDED

#include "driver.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace Driver {

class DriverService final {
 public:
  static constexpr char const* service_full_name() {
    return "Driver.DriverService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::Driver::IdentifyResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>> AsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>>(AsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>> PrepareAsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>>(PrepareAsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::Driver::VerifyResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>> AsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>>(AsyncRouteVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>> PrepareAsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>>(PrepareAsyncRouteVerifyFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::Driver::RegisterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>> AsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>>(AsyncRouteRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>> PrepareAsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>>(PrepareAsyncRouteRegisterFaceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>* AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::IdentifyResult>* PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>* AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::VerifyResult>* PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>* AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Driver::RegisterResponse>* PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::Driver::IdentifyResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>> AsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>>(AsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>> PrepareAsyncRouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>>(PrepareAsyncRouteIdentifyFaceRaw(context, request, cq));
    }
    ::grpc::Status RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::Driver::VerifyResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>> AsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>>(AsyncRouteVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>> PrepareAsyncRouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>>(PrepareAsyncRouteVerifyFaceRaw(context, request, cq));
    }
    ::grpc::Status RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::Driver::RegisterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>> AsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>>(AsyncRouteRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>> PrepareAsyncRouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>>(PrepareAsyncRouteRegisterFaceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, std::function<void(::grpc::Status)>) override;
      void RouteIdentifyFace(::grpc::ClientContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, std::function<void(::grpc::Status)>) override;
      void RouteVerifyFace(::grpc::ClientContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, std::function<void(::grpc::Status)>) override;
      void RouteRegisterFace(::grpc::ClientContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>* AsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Driver::IdentifyResult>* PrepareAsyncRouteIdentifyFaceRaw(::grpc::ClientContext* context, const ::Driver::ImageQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>* AsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Driver::VerifyResult>* PrepareAsyncRouteVerifyFaceRaw(::grpc::ClientContext* context, const ::Driver::VerifyImagePair& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>* AsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Driver::RegisterResponse>* PrepareAsyncRouteRegisterFaceRaw(::grpc::ClientContext* context, const ::Driver::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RouteIdentifyFace_;
    const ::grpc::internal::RpcMethod rpcmethod_RouteVerifyFace_;
    const ::grpc::internal::RpcMethod rpcmethod_RouteRegisterFace_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response);
    virtual ::grpc::Status RouteVerifyFace(::grpc::ServerContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response);
    virtual ::grpc::Status RouteRegisterFace(::grpc::ServerContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteIdentifyFace(::grpc::ServerContext* context, ::Driver::ImageQuery* request, ::grpc::ServerAsyncResponseWriter< ::Driver::IdentifyResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteVerifyFace(::grpc::ServerContext* context, ::Driver::VerifyImagePair* request, ::grpc::ServerAsyncResponseWriter< ::Driver::VerifyResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteRegisterFace(::grpc::ServerContext* context, ::Driver::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::Driver::RegisterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RouteIdentifyFace<WithAsyncMethod_RouteVerifyFace<WithAsyncMethod_RouteRegisterFace<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Driver::ImageQuery, ::Driver::IdentifyResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Driver::ImageQuery* request, ::Driver::IdentifyResult* response) { return this->RouteIdentifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteIdentifyFace(
        ::grpc::MessageAllocator< ::Driver::ImageQuery, ::Driver::IdentifyResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Driver::ImageQuery, ::Driver::IdentifyResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteIdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Driver::VerifyImagePair, ::Driver::VerifyResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Driver::VerifyImagePair* request, ::Driver::VerifyResult* response) { return this->RouteVerifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteVerifyFace(
        ::grpc::MessageAllocator< ::Driver::VerifyImagePair, ::Driver::VerifyResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Driver::VerifyImagePair, ::Driver::VerifyResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteVerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::Driver::RegisterRequest, ::Driver::RegisterResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Driver::RegisterRequest* request, ::Driver::RegisterResponse* response) { return this->RouteRegisterFace(context, request, response); }));}
    void SetMessageAllocatorFor_RouteRegisterFace(
        ::grpc::MessageAllocator< ::Driver::RegisterRequest, ::Driver::RegisterResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Driver::RegisterRequest, ::Driver::RegisterResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteRegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RouteIdentifyFace<WithCallbackMethod_RouteVerifyFace<WithCallbackMethod_RouteRegisterFace<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteIdentifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteVerifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouteRegisterFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteIdentifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteIdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteVerifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteVerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RouteRegisterFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RouteRegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteIdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteIdentifyFace() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Driver::ImageQuery, ::Driver::IdentifyResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Driver::ImageQuery, ::Driver::IdentifyResult>* streamer) {
                       return this->StreamedRouteIdentifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteIdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteIdentifyFace(::grpc::ServerContext* /*context*/, const ::Driver::ImageQuery* /*request*/, ::Driver::IdentifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteIdentifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Driver::ImageQuery,::Driver::IdentifyResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteVerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteVerifyFace() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Driver::VerifyImagePair, ::Driver::VerifyResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Driver::VerifyImagePair, ::Driver::VerifyResult>* streamer) {
                       return this->StreamedRouteVerifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteVerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteVerifyFace(::grpc::ServerContext* /*context*/, const ::Driver::VerifyImagePair* /*request*/, ::Driver::VerifyResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteVerifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Driver::VerifyImagePair,::Driver::VerifyResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RouteRegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RouteRegisterFace() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Driver::RegisterRequest, ::Driver::RegisterResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Driver::RegisterRequest, ::Driver::RegisterResponse>* streamer) {
                       return this->StreamedRouteRegisterFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RouteRegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RouteRegisterFace(::grpc::ServerContext* /*context*/, const ::Driver::RegisterRequest* /*request*/, ::Driver::RegisterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouteRegisterFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Driver::RegisterRequest,::Driver::RegisterResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RouteIdentifyFace<WithStreamedUnaryMethod_RouteVerifyFace<WithStreamedUnaryMethod_RouteRegisterFace<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RouteIdentifyFace<WithStreamedUnaryMethod_RouteVerifyFace<WithStreamedUnaryMethod_RouteRegisterFace<Service > > > StreamedService;
};

}  // namespace Driver


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_driver_2eproto__INCLUDED
