// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: executor.proto

#include "executor.pb.h"
#include "executor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace Executor {

static const char* ExecutorService_method_names[] = {
  "/Executor.ExecutorService/RegisterFace",
  "/Executor.ExecutorService/IdentifyFace",
  "/Executor.ExecutorService/VerifyFace",
};

std::unique_ptr< ExecutorService::Stub> ExecutorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ExecutorService::Stub> stub(new ExecutorService::Stub(channel, options));
  return stub;
}

ExecutorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterFace_(ExecutorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IdentifyFace_(ExecutorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VerifyFace_(ExecutorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ExecutorService::Stub::RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::Executor::RegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Executor::RegisterRequest, ::Executor::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterFace_, context, request, response);
}

void ExecutorService::Stub::async::RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Executor::RegisterRequest, ::Executor::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterFace_, context, request, response, std::move(f));
}

void ExecutorService::Stub::async::RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>* ExecutorService::Stub::PrepareAsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Executor::RegisterReply, ::Executor::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>* ExecutorService::Stub::AsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ExecutorService::Stub::IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::Executor::IdentifyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Executor::IdentifyRequest, ::Executor::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IdentifyFace_, context, request, response);
}

void ExecutorService::Stub::async::IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Executor::IdentifyRequest, ::Executor::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IdentifyFace_, context, request, response, std::move(f));
}

void ExecutorService::Stub::async::IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IdentifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>* ExecutorService::Stub::PrepareAsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Executor::IdentifyReply, ::Executor::IdentifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IdentifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>* ExecutorService::Stub::AsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIdentifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ExecutorService::Stub::VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::Executor::VerifyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Executor::VerifyRequest, ::Executor::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifyFace_, context, request, response);
}

void ExecutorService::Stub::async::VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Executor::VerifyRequest, ::Executor::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyFace_, context, request, response, std::move(f));
}

void ExecutorService::Stub::async::VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyFace_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>* ExecutorService::Stub::PrepareAsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Executor::VerifyReply, ::Executor::VerifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyFace_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>* ExecutorService::Stub::AsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifyFaceRaw(context, request, cq);
  result->StartCall();
  return result;
}

ExecutorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutorService::Service, ::Executor::RegisterRequest, ::Executor::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Executor::RegisterRequest* req,
             ::Executor::RegisterReply* resp) {
               return service->RegisterFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutorService::Service, ::Executor::IdentifyRequest, ::Executor::IdentifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Executor::IdentifyRequest* req,
             ::Executor::IdentifyReply* resp) {
               return service->IdentifyFace(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExecutorService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExecutorService::Service, ::Executor::VerifyRequest, ::Executor::VerifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExecutorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Executor::VerifyRequest* req,
             ::Executor::VerifyReply* resp) {
               return service->VerifyFace(ctx, req, resp);
             }, this)));
}

ExecutorService::Service::~Service() {
}

::grpc::Status ExecutorService::Service::RegisterFace(::grpc::ServerContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ExecutorService::Service::IdentifyFace(::grpc::ServerContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ExecutorService::Service::VerifyFace(::grpc::ServerContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Executor
#include <grpcpp/ports_undef.inc>

