# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import executor_pb2 as executor__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeSimilarity = channel.unary_unary(
                '/executor.ExecutorService/ComputeSimilarity',
                request_serializer=executor__pb2.ComputeRequest.SerializeToString,
                response_deserializer=executor__pb2.ComputeResponse.FromString,
                _registered_method=True)
        self.VerifyFaces = channel.unary_unary(
                '/executor.ExecutorService/VerifyFaces',
                request_serializer=executor__pb2.VerifyRequest.SerializeToString,
                response_deserializer=executor__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.RegisterFace = channel.unary_unary(
                '/executor.ExecutorService/RegisterFace',
                request_serializer=executor__pb2.RegisterRequest.SerializeToString,
                response_deserializer=executor__pb2.RegisterResponse.FromString,
                _registered_method=True)


class ExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSimilarity,
                    request_deserializer=executor__pb2.ComputeRequest.FromString,
                    response_serializer=executor__pb2.ComputeResponse.SerializeToString,
            ),
            'VerifyFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyFaces,
                    request_deserializer=executor__pb2.VerifyRequest.FromString,
                    response_serializer=executor__pb2.VerifyResponse.SerializeToString,
            ),
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=executor__pb2.RegisterRequest.FromString,
                    response_serializer=executor__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.ExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/ComputeSimilarity',
            executor__pb2.ComputeRequest.SerializeToString,
            executor__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/VerifyFaces',
            executor__pb2.VerifyRequest.SerializeToString,
            executor__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.ExecutorService/RegisterFace',
            executor__pb2.RegisterRequest.SerializeToString,
            executor__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
