# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\x1a\x0c\x63ommon.proto\"0\n\tFaceMatch\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\"$\n\x0e\x43omputeRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"e\n\x0f\x43omputeResponse\x12\x14\n\x0c\x62\x65st_user_id\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\x12(\n\x0btop_matches\x18\x03 \x03(\x0b\x32\x13.executor.FaceMatch\"/\n\rVerifyRequest\x12\x0e\n\x06image1\x18\x01 \x01(\x0c\x12\x0e\n\x06image2\x18\x02 \x01(\x0c\"4\n\x0eVerifyResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x12\x0e\n\x06result\x18\x02 \x01(\t\"T\n\x0fRegisterRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06origin\x18\x04 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe4\x01\n\x0f\x45xecutorService\x12H\n\x11\x43omputeSimilarity\x12\x18.executor.ComputeRequest\x1a\x19.executor.ComputeResponse\x12@\n\x0bVerifyFaces\x12\x17.executor.VerifyRequest\x1a\x18.executor.VerifyResponse\x12\x45\n\x0cRegisterFace\x12\x19.executor.RegisterRequest\x1a\x1a.executor.RegisterResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACEMATCH._serialized_start=42
  _FACEMATCH._serialized_end=90
  _COMPUTEREQUEST._serialized_start=92
  _COMPUTEREQUEST._serialized_end=128
  _COMPUTERESPONSE._serialized_start=130
  _COMPUTERESPONSE._serialized_end=231
  _VERIFYREQUEST._serialized_start=233
  _VERIFYREQUEST._serialized_end=280
  _VERIFYRESPONSE._serialized_start=282
  _VERIFYRESPONSE._serialized_end=334
  _REGISTERREQUEST._serialized_start=336
  _REGISTERREQUEST._serialized_end=420
  _REGISTERRESPONSE._serialized_start=422
  _REGISTERRESPONSE._serialized_end=457
  _EXECUTORSERVICE._serialized_start=460
  _EXECUTORSERVICE._serialized_end=688
# @@protoc_insertion_point(module_scope)
