// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: executor.proto
#ifndef GRPC_executor_2eproto__INCLUDED
#define GRPC_executor_2eproto__INCLUDED

#include "executor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace Executor {

class ExecutorService final {
 public:
  static constexpr char const* service_full_name() {
    return "Executor.ExecutorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::Executor::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>> AsyncRegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>>(AsyncRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>> PrepareAsyncRegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>>(PrepareAsyncRegisterFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::Executor::IdentifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>> AsyncIdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>>(AsyncIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>> PrepareAsyncIdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>>(PrepareAsyncIdentifyFaceRaw(context, request, cq));
    }
    virtual ::grpc::Status VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::Executor::VerifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>> AsyncVerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>>(AsyncVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>> PrepareAsyncVerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>>(PrepareAsyncVerifyFaceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>* AsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::RegisterReply>* PrepareAsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>* AsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::IdentifyReply>* PrepareAsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>* AsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Executor::VerifyReply>* PrepareAsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::Executor::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>> AsyncRegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>>(AsyncRegisterFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>> PrepareAsyncRegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>>(PrepareAsyncRegisterFaceRaw(context, request, cq));
    }
    ::grpc::Status IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::Executor::IdentifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>> AsyncIdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>>(AsyncIdentifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>> PrepareAsyncIdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>>(PrepareAsyncIdentifyFaceRaw(context, request, cq));
    }
    ::grpc::Status VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::Executor::VerifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>> AsyncVerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>>(AsyncVerifyFaceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>> PrepareAsyncVerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>>(PrepareAsyncVerifyFaceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterFace(::grpc::ClientContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, std::function<void(::grpc::Status)>) override;
      void IdentifyFace(::grpc::ClientContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, std::function<void(::grpc::Status)>) override;
      void VerifyFace(::grpc::ClientContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>* AsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Executor::RegisterReply>* PrepareAsyncRegisterFaceRaw(::grpc::ClientContext* context, const ::Executor::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>* AsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Executor::IdentifyReply>* PrepareAsyncIdentifyFaceRaw(::grpc::ClientContext* context, const ::Executor::IdentifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>* AsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Executor::VerifyReply>* PrepareAsyncVerifyFaceRaw(::grpc::ClientContext* context, const ::Executor::VerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterFace_;
    const ::grpc::internal::RpcMethod rpcmethod_IdentifyFace_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyFace_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterFace(::grpc::ServerContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response);
    virtual ::grpc::Status IdentifyFace(::grpc::ServerContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response);
    virtual ::grpc::Status VerifyFace(::grpc::ServerContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterFace() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterFace(::grpc::ServerContext* context, ::Executor::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::Executor::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIdentifyFace(::grpc::ServerContext* context, ::Executor::IdentifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::Executor::IdentifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyFace() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyFace(::grpc::ServerContext* context, ::Executor::VerifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::Executor::VerifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterFace<WithAsyncMethod_IdentifyFace<WithAsyncMethod_VerifyFace<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterFace() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Executor::RegisterRequest, ::Executor::RegisterReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Executor::RegisterRequest* request, ::Executor::RegisterReply* response) { return this->RegisterFace(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterFace(
        ::grpc::MessageAllocator< ::Executor::RegisterRequest, ::Executor::RegisterReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Executor::RegisterRequest, ::Executor::RegisterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Executor::IdentifyRequest, ::Executor::IdentifyReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Executor::IdentifyRequest* request, ::Executor::IdentifyReply* response) { return this->IdentifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_IdentifyFace(
        ::grpc::MessageAllocator< ::Executor::IdentifyRequest, ::Executor::IdentifyReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Executor::IdentifyRequest, ::Executor::IdentifyReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyFace() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::Executor::VerifyRequest, ::Executor::VerifyReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Executor::VerifyRequest* request, ::Executor::VerifyReply* response) { return this->VerifyFace(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyFace(
        ::grpc::MessageAllocator< ::Executor::VerifyRequest, ::Executor::VerifyReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Executor::VerifyRequest, ::Executor::VerifyReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterFace<WithCallbackMethod_IdentifyFace<WithCallbackMethod_VerifyFace<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterFace() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyFace() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterFace() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIdentifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyFace() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyFace(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterFace() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IdentifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IdentifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyFace() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyFace(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyFace(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterFace() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Executor::RegisterRequest, ::Executor::RegisterReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Executor::RegisterRequest, ::Executor::RegisterReply>* streamer) {
                       return this->StreamedRegisterFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterFace(::grpc::ServerContext* /*context*/, const ::Executor::RegisterRequest* /*request*/, ::Executor::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Executor::RegisterRequest,::Executor::RegisterReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IdentifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IdentifyFace() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Executor::IdentifyRequest, ::Executor::IdentifyReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Executor::IdentifyRequest, ::Executor::IdentifyReply>* streamer) {
                       return this->StreamedIdentifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IdentifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IdentifyFace(::grpc::ServerContext* /*context*/, const ::Executor::IdentifyRequest* /*request*/, ::Executor::IdentifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIdentifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Executor::IdentifyRequest,::Executor::IdentifyReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyFace : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyFace() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Executor::VerifyRequest, ::Executor::VerifyReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Executor::VerifyRequest, ::Executor::VerifyReply>* streamer) {
                       return this->StreamedVerifyFace(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyFace() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyFace(::grpc::ServerContext* /*context*/, const ::Executor::VerifyRequest* /*request*/, ::Executor::VerifyReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyFace(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Executor::VerifyRequest,::Executor::VerifyReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterFace<WithStreamedUnaryMethod_IdentifyFace<WithStreamedUnaryMethod_VerifyFace<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterFace<WithStreamedUnaryMethod_IdentifyFace<WithStreamedUnaryMethod_VerifyFace<Service > > > StreamedService;
};

}  // namespace Executor


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_executor_2eproto__INCLUDED
