syntax = "proto3";

package Executor;

service ExecutorService {
  rpc RegisterFace (RegisterRequest) returns (RegisterReply);
  rpc IdentifyFace (IdentifyRequest) returns (IdentifyReply);
  rpc VerifyFace (VerifyRequest) returns (VerifyReply);
}

message RegisterRequest {
  string user_id = 1;
  string name = 2;
  string origin = 3;
  bytes image_data = 4;
}

message RegisterReply {
  string user_id = 1;
  string message = 2;
}

message IdentifyRequest {
  bytes image_data = 1;
}

message IdentifyReply {
  repeated FaceResult results = 1;
}

message FaceResult {
  int32 face_index = 1;
  repeated Candidate top_matches = 2;
  bytes crop_image = 3;
}

message Candidate {
  string user_id = 1;
  float confidence = 2;
}

message VerifyRequest {
  bytes image1 = 1;
  bytes image2 = 2;
}

message VerifyReply {
  float similarity = 1;
  string result = 2;
}