syntax = "proto3";
package executor;

import "common.proto";

service ExecutorService {
  rpc ComputeSimilarity (ComputeRequest) returns (ComputeResponse);
  rpc VerifyFaces (VerifyRequest) returns (VerifyResponse);
  rpc RegisterFace (RegisterRequest) returns (RegisterResponse);
  rpc DeleteFace (DeleteRequest) returns (DeleteResponse);
  rpc GetUserId (NameOriginQuery) returns (UserIdResult);
}

message FaceMatch {
  string user_id = 1;
  float similarity = 2;
}

message FaceResult {
  int32 face_index = 1;
  repeated FaceMatch top_matches = 2;
  bytes crop_image = 3;
}

message ComputeRequest {
  bytes image_data = 1;
}

message ComputeResponse {
  repeated FaceResult results = 1;
}

message VerifyRequest {
  bytes image1 = 1;
  bytes image2 = 2;
}

message VerifyResponse {
  float similarity = 1;
  string result = 2;
}

message RegisterRequest {
  bytes image_data = 1;
  string user_id = 2;
  string name = 3;
  string origin = 4;
}

message RegisterResponse {
  string message = 1;
}

message DeleteRequest {
  string user_id = 1;
}

message DeleteResponse {
  string message = 1;
}

message NameOriginQuery {
  string name = 1;
  string origin = 2;
}

message UserIdResult {
  string user_id = 1;
}