# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import executor_pb2 as executor__pb2


class ExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeSimilarity = channel.unary_unary(
                '/executor.ExecutorService/ComputeSimilarity',
                request_serializer=executor__pb2.ComputeRequest.SerializeToString,
                response_deserializer=executor__pb2.ComputeResponse.FromString,
                )
        self.VerifyFaces = channel.unary_unary(
                '/executor.ExecutorService/VerifyFaces',
                request_serializer=executor__pb2.VerifyRequest.SerializeToString,
                response_deserializer=executor__pb2.VerifyResponse.FromString,
                )
        self.RegisterFace = channel.unary_unary(
                '/executor.ExecutorService/RegisterFace',
                request_serializer=executor__pb2.RegisterRequest.SerializeToString,
                response_deserializer=executor__pb2.RegisterResponse.FromString,
                )


class ExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSimilarity,
                    request_deserializer=executor__pb2.ComputeRequest.FromString,
                    response_serializer=executor__pb2.ComputeResponse.SerializeToString,
            ),
            'VerifyFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyFaces,
                    request_deserializer=executor__pb2.VerifyRequest.FromString,
                    response_serializer=executor__pb2.VerifyResponse.SerializeToString,
            ),
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=executor__pb2.RegisterRequest.FromString,
                    response_serializer=executor__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.ExecutorService/ComputeSimilarity',
            executor__pb2.ComputeRequest.SerializeToString,
            executor__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.ExecutorService/VerifyFaces',
            executor__pb2.VerifyRequest.SerializeToString,
            executor__pb2.VerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executor.ExecutorService/RegisterFace',
            executor__pb2.RegisterRequest.SerializeToString,
            executor__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
