# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoimport common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\x1a\x0c\x63ommon.proto\"!\n\x0b\x46\x61\x63\x65Request\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"I\n\x0c\x46\x61\x63\x65Response\x12(\n\tembedding\x18\x01 \x01(\x0b\x32\x15.common.FaceEmbedding\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\rWorkerService\x12\x38\n\x0bProcessFace\x12\x13.worker.FaceRequest\x1a\x14.worker.FaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEREQUEST']._serialized_start=38
  _globals['_FACEREQUEST']._serialized_end=71
  _globals['_FACERESPONSE']._serialized_start=73
  _globals['_FACERESPONSE']._serialized_end=146
  _globals['_WORKERSERVICE']._serialized_start=148
  _globals['_WORKERSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
